In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('pokedex.csv')

In [6]:
data.head(10)

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,...,2.0,1.0,1.0,0.50,2.0,1.0,1.0,1.0,0.5,0.5
5,5,5,Charmeleon,Glutexo,リザード (Lizardo),1,Normal,Flame Pokémon,1,Fire,...,2.0,1.0,1.0,0.50,2.0,1.0,1.0,1.0,0.5,0.5
6,6,6,Charizard,Glurak,リザードン (Lizardon),1,Normal,Flame Pokémon,2,Fire,...,0.0,1.0,1.0,0.25,4.0,1.0,1.0,1.0,0.5,0.5
7,7,6,Mega Charizard X,Glurak,リザードン (Lizardon),1,Normal,Flame Pokémon,2,Fire,...,2.0,1.0,1.0,0.50,2.0,1.0,2.0,1.0,0.5,1.0
8,8,6,Mega Charizard Y,Glurak,リザードン (Lizardon),1,Normal,Flame Pokémon,2,Fire,...,0.0,1.0,1.0,0.25,4.0,1.0,1.0,1.0,0.5,0.5
9,9,7,Squirtle,Schiggy,ゼニガメ (Zenigame),1,Normal,Tiny Turtle Pokémon,1,Water,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0

In [12]:
def getRegionName(generation):
    region = {1: 'Kanto', 2: 'Johto', 3: 'Hoenn', 4: 'Sinnoh', 5: 'Unova', 6: 'Kalos', 7: 'Alola', 8: 'Galar'}
    return region[generation]

In [14]:
data['region_name'] = data['generation'].apply(getRegionName)

In [15]:
data

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,region_name
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,...,1.0,1.0,0.50,2.00,1.0,1.0,1.0,0.5,0.5,Kanto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,1023,888,Zacian Hero of Many Battles,NaN,NaN,8,Legendary,Warrior Pokémon,1,Fairy,...,1.0,1.0,0.50,1.00,1.0,0.0,0.5,2.0,1.0,Galar
1024,1024,889,Zamazenta Crowned Shield,NaN,NaN,8,Legendary,Warrior Pokémon,2,Fighting,...,1.0,1.0,0.25,0.25,1.0,0.5,0.5,0.5,1.0,Galar
1025,1025,889,Zamazenta Hero of Many Battles,NaN,NaN,8,Legendary,Warrior Pokémon,1,Fighting,...,2.0,2.0,0.50,0.50,1.0,1.0,0.5,1.0,2.0,Galar
1026,1026,890,Eternatus,NaN,NaN,8,Legendary,Gigantic Pokémon,2,Poison,...,1.0,2.0,0.50,1.00,1.0,2.0,1.0,1.0,1.0,Galar
1027,1027,890,Eternatus Eternamax,NaN,NaN,8,Legendary,Gigantic Pokémon,2,Poison,...,1.0,2.0,0.50,1.00,1.0,2.0,1.0,1.0,1.0,Galar

In [17]:
data = data.drop(['german_name', 'japanese_name'], axis=1)

In [18]:
data

,Unnamed: 0,pokedex_number,name,generation,status,species,type_number,type_1,type_2,height_m,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,region_name
0,0,1,Bulbasaur,1,Normal,Seed Pokémon,2,Grass,Poison,0.7,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
1,1,2,Ivysaur,1,Normal,Seed Pokémon,2,Grass,Poison,1.0,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
2,2,3,Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.0,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
3,3,3,Mega Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.4,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
4,4,4,Charmander,1,Normal,Lizard Pokémon,1,Fire,NaN,0.6,...,1.0,1.0,0.50,2.00,1.0,1.0,1.0,0.5,0.5,Kanto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,1023,888,Zacian Hero of Many Battles,8,Legendary,Warrior Pokémon,1,Fairy,NaN,2.8,...,1.0,1.0,0.50,1.00,1.0,0.0,0.5,2.0,1.0,Galar
1024,1024,889,Zamazenta Crowned Shield,8,Legendary,Warrior Pokémon,2,Fighting,Steel,2.9,...,1.0,1.0,0.25,0.25,1.0,0.5,0.5,0.5,1.0,Galar
1025,1025,889,Zamazenta Hero of Many Battles,8,Legendary,Warrior Pokémon,1,Fighting,NaN,2.9,...,2.0,2.0,0.50,0.50,1.0,1.0,0.5,1.0,2.0,Galar
1026,1026,890,Eternatus,8,Legendary,Gigantic Pokémon,2,Poison,Dragon,20.0,...,1.0,2.0,0.50,1.00,1.0,2.0,1.0,1.0,1.0,Galar
1027,1027,890,Eternatus Eternamax,8,Legendary,Gigantic Pokémon,2,Poison,Dragon,100.0,...,1.0,2.0,0.50,1.00,1.0,2.0,1.0,1.0,1.0,Galar

In [21]:
data['pokedex_number'].count()

1028

In [33]:
data['status'].unique()

array(['Normal', 'Sub Legendary', 'Legendary', 'Mythical'], dtype=object)

In [35]:
data = data.drop('type_number', axis=1)

In [36]:
data

,Unnamed: 0,pokedex_number,name,generation,status,species,type_1,type_2,height_m,weight_kg,...,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,region_name
0,0,1,Bulbasaur,1,Normal,Seed Pokémon,Grass,Poison,0.7,6.9,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
1,1,2,Ivysaur,1,Normal,Seed Pokémon,Grass,Poison,1.0,13.0,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
2,2,3,Venusaur,1,Normal,Seed Pokémon,Grass,Poison,2.0,100.0,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
3,3,3,Mega Venusaur,1,Normal,Seed Pokémon,Grass,Poison,2.4,155.5,...,2.0,2.0,1.00,1.00,1.0,1.0,1.0,1.0,0.5,Kanto
4,4,4,Charmander,1,Normal,Lizard Pokémon,Fire,NaN,0.6,8.5,...,1.0,1.0,0.50,2.00,1.0,1.0,1.0,0.5,0.5,Kanto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,1023,888,Zacian Hero of Many Battles,8,Legendary,Warrior Pokémon,Fairy,NaN,2.8,110.0,...,1.0,1.0,0.50,1.00,1.0,0.0,0.5,2.0,1.0,Galar
1024,1024,889,Zamazenta Crowned Shield,8,Legendary,Warrior Pokémon,Fighting,Steel,2.9,785.0,...,1.0,1.0,0.25,0.25,1.0,0.5,0.5,0.5,1.0,Galar
1025,1025,889,Zamazenta Hero of Many Battles,8,Legendary,Warrior Pokémon,Fighting,NaN,2.9,210.0,...,2.0,2.0,0.50,0.50,1.0,1.0,0.5,1.0,2.0,Galar
1026,1026,890,Eternatus,8,Legendary,Gigantic Pokémon,Poison,Dragon,20.0,950.0,...,1.0,2.0,0.50,1.00,1.0,2.0,1.0,1.0,1.0,Galar
1027,1027,890,Eternatus Eternamax,8,Legendary,Gigantic Pokémon,Poison,Dragon,100.0,NaN,...,1.0,2.0,0.50,1.00,1.0,2.0,1.0,1.0,1.0,Galar

In [38]:
data.columns

Index(['Unnamed: 0', 'pokedex_number', 'name', 'generation', 'status',
       'species', 'type_1', 'type_2', 'height_m', 'weight_kg',
       'abilities_number', 'ability_1', 'ability_2', 'ability_hidden',
       'total_points', 'hp', 'attack', 'defense', 'sp_attack', 'sp_defense',
       'speed', 'catch_rate', 'base_friendship', 'base_experience',
       'growth_rate', 'egg_type_number', 'egg_type_1', 'egg_type_2',
       'percentage_male', 'egg_cycles', 'against_normal', 'against_fire',
       'against_water', 'against_electric', 'against_grass', 'against_ice',
       'against_fight', 'against_poison', 'against_ground', 'against_flying',
       'against_psychic', 'against_bug', 'against_rock', 'against_ghost',
       'against_dragon', 'against_dark', 'against_steel', 'against_fairy',
       'region_name'],
      dtype='object')

In [40]:
data = data.drop(['growth_rate', 'egg_type_number', 'egg_type_1', 'egg_type_2', 'egg_cycles', 'Unnamed: 0'], axis=1)

In [41]:
data.columns

Index(['pokedex_number', 'name', 'generation', 'status', 'species', 'type_1',
       'type_2', 'height_m', 'weight_kg', 'abilities_number', 'ability_1',
       'ability_2', 'ability_hidden', 'total_points', 'hp', 'attack',
       'defense', 'sp_attack', 'sp_defense', 'speed', 'catch_rate',
       'base_friendship', 'base_experience', 'percentage_male',
       'against_normal', 'against_fire', 'against_water', 'against_electric',
       'against_grass', 'against_ice', 'against_fight', 'against_poison',
       'against_ground', 'against_flying', 'against_psychic', 'against_bug',
       'against_rock', 'against_ghost', 'against_dragon', 'against_dark',
       'against_steel', 'against_fairy', 'region_name'],
      dtype='object')

In [42]:
data = data.drop(['base_friendship', 'base_experience'], axis = 1)

In [43]:
data.columns

Index(['pokedex_number', 'name', 'generation', 'status', 'species', 'type_1',
       'type_2', 'height_m', 'weight_kg', 'abilities_number', 'ability_1',
       'ability_2', 'ability_hidden', 'total_points', 'hp', 'attack',
       'defense', 'sp_attack', 'sp_defense', 'speed', 'catch_rate',
       'percentage_male', 'against_normal', 'against_fire', 'against_water',
       'against_electric', 'against_grass', 'against_ice', 'against_fight',
       'against_poison', 'against_ground', 'against_flying', 'against_psychic',
       'against_bug', 'against_rock', 'against_ghost', 'against_dragon',
       'against_dark', 'against_steel', 'against_fairy', 'region_name'],
      dtype='object')

In [46]:
data = data.drop(['against_normal', 'against_fire', 'against_water', 'against_electric', 'against_grass', 'against_ice', 'against_fight', 'against_poison', 'against_ground', 'against_flying', 'against_psychic', 'against_bug', 'against_rock', 'against_ghost', 'against_dragon', 'against_dark', 'against_steel', 'against_fairy'], axis = 1)

In [47]:
data

,pokedex_number,name,generation,status,species,type_1,type_2,height_m,weight_kg,abilities_number,...,total_points,hp,attack,defense,sp_attack,sp_defense,speed,catch_rate,percentage_male,region_name
0,1,Bulbasaur,1,Normal,Seed Pokémon,Grass,Poison,0.7,6.9,2,...,318.0,45.0,49.0,49.0,65.0,65.0,45.0,45.0,87.5,Kanto
1,2,Ivysaur,1,Normal,Seed Pokémon,Grass,Poison,1.0,13.0,2,...,405.0,60.0,62.0,63.0,80.0,80.0,60.0,45.0,87.5,Kanto
2,3,Venusaur,1,Normal,Seed Pokémon,Grass,Poison,2.0,100.0,2,...,525.0,80.0,82.0,83.0,100.0,100.0,80.0,45.0,87.5,Kanto
3,3,Mega Venusaur,1,Normal,Seed Pokémon,Grass,Poison,2.4,155.5,1,...,625.0,80.0,100.0,123.0,122.0,120.0,80.0,45.0,87.5,Kanto
4,4,Charmander,1,Normal,Lizard Pokémon,Fire,NaN,0.6,8.5,2,...,309.0,39.0,52.0,43.0,60.0,50.0,65.0,45.0,87.5,Kanto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,888,Zacian Hero of Many Battles,8,Legendary,Warrior Pokémon,Fairy,NaN,2.8,110.0,1,...,670.0,92.0,130.0,115.0,80.0,115.0,138.0,NaN,NaN,Galar
1024,889,Zamazenta Crowned Shield,8,Legendary,Warrior Pokémon,Fighting,Steel,2.9,785.0,1,...,720.0,92.0,130.0,145.0,80.0,145.0,128.0,NaN,NaN,Galar
1025,889,Zamazenta Hero of Many Battles,8,Legendary,Warrior Pokémon,Fighting,NaN,2.9,210.0,1,...,670.0,92.0,130.0,115.0,80.0,115.0,138.0,NaN,NaN,Galar
1026,890,Eternatus,8,Legendary,Gigantic Pokémon,Poison,Dragon,20.0,950.0,1,...,690.0,140.0,85.0,95.0,145.0,95.0,130.0,NaN,NaN,Galar
1027,890,Eternatus Eternamax,8,Legendary,Gigantic Pokémon,Poison,Dragon,100.0,NaN,0,...,1125.0,255.0,115.0,250.0,125.0,250.0,130.0,NaN,NaN,Galar

In [50]:
data.to_csv('pokedex-slim.csv', index=False)